# SPDX-FileCopyrightText: 2026 Dingtaiqi
# SPDX-License-Identifier: AGPL-3.0-or-later
# ===========================================================================
#  gen_dhgroups.ps1 - fetch the FFDHE groups from RFC 7919 and emit them as C++.
#
#  Why fetch instead of typing: a 2048/3072/4096-bit prime is exactly the kind of
#  constant that gets mistyped, and CNG validates the modulus, so a wrong digit is a
#  hard failure with no useful message.  This script downloads the RFC (caching it),
#  finds each group's prime block, VERIFIES it (length, that it starts and ends with
#  all-ones like every FFDHE prime, that p mod 8 == 7, and that (p-1)/2 is prime -
#  a safe prime is what CNG's DH requires), and writes src/nvmeof_dhgroups.h.
#
#  The groups are what NVMe-oF names for NVME_AUTH_DHGROUP_2048/3072/4096 (RFC 7919
#  negotiated FF-DHE, generator 2), so interop uses exactly these bytes.
#
#  Finding the primes: the phrase "The hexadecimal representation of p is:" is wrapped
#  across lines in the later sections (so matching on it finds only the first group),
#  and the group NAME appears many times before each prime (table of contents, prose).
#  So: collect runs of hex-only lines as prime candidates, and pair each candidate with
#  the nearest preceding "ffdheNNNN".
#
#  Usage: powershell -File gen_dhgroups.ps1
# ===========================================================================
$ErrorActionPreference = 'Stop'
$cache = Join-Path $PSScriptRoot 'rfc7919.txt'
if (-not (Test-Path $cache)) {
    $url = 'https://www.rfc-editor.org/rfc/rfc7919.txt'
    Write-Host "fetching $url ..."
    (Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 60).Content |
        Set-Content -Path $cache -Encoding UTF8
} else {
    Write-Host "using cached $cache"
}
$rfc = Get-Content $cache -Raw
if ($rfc -notmatch 'ffdhe2048') { throw "the cached document does not look like RFC 7919" }

function Get-PrimeCandidates([string]$text) {
    $ls = $text -split "\r?\n"
    $cands = @()
    $hex = ''
    $startLine = 0
    for ($i = 0; $i -lt $ls.Count; $i++) {
        # Page furniture ("RFC 7919 ... August 2016", "[Page 26]", bare page numbers)
        # sits INSIDE the long hex blocks of the bigger groups, so it must not end a
        # run: doing so split the 4096-bit prime into a 1008-hex-char piece plus a
        # remainder, and the length check then said "got 1008, expected 1024".
        if ($ls[$i] -match 'RFC 7919' -and $ls[$i] -match 'Page') { continue }
        if ($ls[$i] -match '^\s*\[?Page\s+\d+\]?\s*$') { continue }
        if ($ls[$i] -match '^\s*\d+\s*$') { continue }
        if ($ls[$i] -match '^\s*\f\s*$') { continue }
        $stripped = ($ls[$i] -replace '\s', '')
        # >= 8 characters, not >= 32: the LAST line of every prime block is short
        # (it holds just the trailing FFFFFFFF FFFFFFFF), and a higher threshold
        # dropped that line and ended the run - which is why the 4096-bit prime came
        # out as 1008 hex characters instead of 1024.
        $isHexLine = ($stripped.Length -ge 8) -and ($stripped -match '^[0-9a-fA-F]+$')
        if ($isHexLine) {
            if ($hex.Length -eq 0) { $startLine = $i }
            $hex += $stripped
        } else {
            if ($hex.Length -ge 512) { $cands += [pscustomobject]@{ hex = $hex; line = $startLine } }
            $hex = ''
        }
    }
    if ($hex.Length -ge 512) { $cands += [pscustomobject]@{ hex = $hex; line = $startLine } }
    return $cands
}

function Name-Before([string[]]$ls, [int]$line) {
    for ($i = $line; $i -ge 0; $i--) {
        $m = [regex]::Match($ls[$i], 'ffdhe\d{4}')
        if ($m.Success) { return $m.Value }
    }
    return $null
}

$lines = $rfc -split "\r?\n"
$cands = Get-PrimeCandidates $rfc
Write-Host "prime candidates found: $($cands.Count)"
$byName = @{}
foreach ($c in $cands) {
    $n = Name-Before $lines $c.line
    if ($n -and -not $byName.ContainsKey($n)) {
        $byName[$n] = $c.hex
        Write-Host "  $n -> $($c.hex.Length) hex chars"
    }
}

$two = [System.Numerics.BigInteger]2
function Hex-Bytes([string]$hex) {
    $n = $hex.Length / 2
    $b = New-Object byte[] $n
    for ($i = 0; $i -lt $n; $i++) { $b[$i] = [Convert]::ToByte($hex.Substring(2 * $i, 2), 16) }
    return $b
}
function To-BigInt([byte[]]$be) {
    $c = [byte[]]($be.Clone()); [array]::Reverse($c)
    return [System.Numerics.BigInteger]::new([byte[]]($c + [byte]0))
}

$groups = @(
    @{ name = 'kFfdhe2048'; size = 256; rfc = 'ffdhe2048'; bits = 2048 },
    @{ name = 'kFfdhe3072'; size = 384; rfc = 'ffdhe3072'; bits = 3072 },
    @{ name = 'kFfdhe4096'; size = 512; rfc = 'ffdhe4096'; bits = 4096 }
)

$out = New-Object System.Collections.Generic.List[string]
$out.Add('// GENERATED by src/gen_dhgroups.ps1 from RFC 7919 - do not edit by hand.')
$out.Add('//')
$out.Add('// The negotiated FFDHE groups the NVMe-oF spec names for NVME_AUTH_DHGROUP_2048,')
$out.Add('// _3072 and _4096, generator 2.  The generator script verifies each prime''s length,')
$out.Add('// that it starts and ends with all-ones, that p mod 8 == 7 and that (p-1)/2 is')
$out.Add('// prime (CNG''s DH requires a safe prime); it fails loudly rather than emitting a')
$out.Add('// group it could not verify.')
$out.Add('#pragma once')
$out.Add('#include <stdint.h>')
$out.Add('')

foreach ($g in $groups) {
    $hex = $byName[$g.rfc]
    if (-not $hex) { throw "no prime block found for $($g.rfc)" }
    if ($hex.Length -ne $g.size * 2) { throw "$($g.rfc): got $($hex.Length) hex chars, expected $($g.size * 2)" }
    if ($hex.Substring(0, 4) -ne 'ffff' -or $hex.Substring($hex.Length - 4) -ne 'ffff') {
        throw "$($g.rfc): does not look like an FFDHE prime"
    }
    $bytes = Hex-Bytes $hex
    $p = To-BigInt $bytes
    $mod8 = $p % 8
    if ($mod8 -ne 7) { throw "$($g.rfc): p mod 8 = $mod8, expected 7" }
    $half = ($p - 1) / 2
    $composite = $false
    foreach ($sp in 2,3,5,7,11,13,17,19,23,29,31,37) { if ($half % $sp -eq 0) { $composite = ($half -ne $sp) } }
    if (-not $composite) {
        if ([System.Numerics.BigInteger]::ModPow($two, $half - 1, $half) -ne 1) {
            throw "$($g.rfc): (p-1)/2 is not prime - not a safe prime"
        }
    }
    Write-Host "  $($g.rfc): $($g.bits) bits, p mod 8 = 7, (p-1)/2 prime - verified"
    $out.Add("// RFC 7919 $($g.rfc): $($g.bits)-bit MODP group, generator 2.")
    $out.Add("static const uint8_t $($g.name)[$($g.size)] = {")
    for ($i = 0; $i -lt $g.size; $i += 16) {
        $row = @()
        for ($j = 0; $j -lt 16 -and ($i + $j) -lt $g.size; $j++) { $row += '0x' + $hex.Substring(2 * ($i + $j), 2) }
        $out.Add('    ' + ($row -join ', ') + $(if (($i + 16) -lt $g.size) { ',' } else { '' }))
    }
    $out.Add('};')
    $out.Add("static const uint32_t $($g.name)Size = $($g.size);")
    $out.Add('')
}
$file = Join-Path $PSScriptRoot 'nvmeof_dhgroups.h'
[System.IO.File]::WriteAllLines($file, $out)
Write-Host "wrote $file ($((Get-Item $file).Length) bytes)"
