# ===========================================================================
#  run_authselftest.ps1 - check the CNG Diffie-Hellman plumbing against an
#  independent implementation.
#
#  f5_interop.exe -authselftest prints:
#      [dh] privA=<hex> pubA=<hex> privB=<hex> pubB=<hex> shared=<hex>
#  all 256-byte big-endian values for the RFC 7919 ffdhe2048 group in nvmeof_dhgroups.h.
#
#  This script recomputes, with System.Numerics.BigInteger:
#      pubA == 2^privA mod p          (so the private/public pair and its byte order)
#      shared == pubB^privA mod p     and == pubA^privB mod p   (the shared secret)
#  CNG and BigInteger share no code, so agreement here means the values and their
#  byte order are right - which is exactly what a failed handshake cannot tell you.
# ===========================================================================
param([string]$Exe = "$PSScriptRoot\f5_interop.exe")

$ErrorActionPreference = 'Stop'
$two = [System.Numerics.BigInteger]2

# The group is generated by gen_testgroup.ps1; take the prime from the generated
# header so both sides cannot drift apart.
$hdr = Get-Content (Join-Path $PSScriptRoot 'nvmeof_dhgroups.h') -Raw
$m = [regex]::Match($hdr, '(?s)kFfdhe2048\[256\]\s*=\s*\{(.*?)\};')
if (-not $m.Success) { throw "cannot find kFfdhe2048 in nvmeof_dhgroups.h" }
$bytes = [regex]::Matches($m.Groups[1].Value, '0x([0-9a-fA-F]{2})') | ForEach-Object { [Convert]::ToByte($_.Groups[1].Value, 16) }
if ($bytes.Count -ne 256) { throw "kFfdhe2048 has $($bytes.Count) bytes, expected 256" }
# BigInteger(byte[]) is LITTLE-endian, so reverse to get the big-endian value.
[array]::Reverse($bytes)
$p = [System.Numerics.BigInteger]::new([byte[]]($bytes + [byte]0))

function Parse-BeHex([string]$hex) {
    $b = New-Object byte[] ($hex.Length / 2)
    for ($i = 0; $i -lt $b.Length; $i++) { $b[$i] = [Convert]::ToByte($hex.Substring(2 * $i, 2), 16) }
    [array]::Reverse($b)
    return [System.Numerics.BigInteger]::new([byte[]]($b + [byte]0))
}
function Hex-Be([System.Numerics.BigInteger]$v) {
    $h = $v.ToString('x'); if ($h.Length -eq 513) { $h = $h.Substring(1) }
    return $h.PadLeft(512, '0')
}

$out = & $Exe -authselftest 2>&1
$val = @{}
foreach ($line in $out) {
    $mm = [regex]::Match($line, '\[dh\]\s+(\w+)=([0-9a-f]{512})')
    if ($mm.Success) { $val[$mm.Groups[1].Value] = $mm.Groups[2].Value }
}
foreach ($need in 'privA','pubA','privB','pubB','shared') {
    if (-not $val.ContainsKey($need)) { throw "the self-test did not print [dh] $need" }
}

$fail = 0
function Check([string]$what, [bool]$ok, [string]$detail) {
    if ($ok) { Write-Host "  [PASS] $what" }
    else { Write-Host "  [FAIL] $what - $detail"; $script:fail++ }
}

$privA = Parse-BeHex $val['privA']; $pubA = Parse-BeHex $val['pubA']
$privB = Parse-BeHex $val['privB']; $pubB = Parse-BeHex $val['pubB']
$sh    = Parse-BeHex $val['shared']

Check "pubA == 2^privA mod p (CNG pair, byte order included)" `
      ([System.Numerics.BigInteger]::ModPow($two, $privA, $p) -eq $pubA) `
      "computed $((Hex-Be ([System.Numerics.BigInteger]::ModPow($two, $privA, $p))).Substring(0,16))... got $($val['pubA'].Substring(0,16))..."
Check "pubB == 2^privB mod p" `
      ([System.Numerics.BigInteger]::ModPow($two, $privB, $p) -eq $pubB) "mismatch"
Check "shared == pubB^privA mod p (CNG secret, byte order included)" `
      ([System.Numerics.BigInteger]::ModPow($pubB, $privA, $p) -eq $sh) `
      "computed $((Hex-Be ([System.Numerics.BigInteger]::ModPow($pubB, $privA, $p))).Substring(0,16))... got $($val['shared'].Substring(0,16))..."
Check "shared == pubA^privB mod p (the other direction)" `
      ([System.Numerics.BigInteger]::ModPow($pubA, $privB, $p) -eq $sh) "mismatch"

Write-Host ""
if ($fail -eq 0) { Write-Host "CNG vs BigInteger: all DH values agree" } else { Write-Host "$fail DH check(s) FAILED" }
exit $fail
