#!/bin/sh
# SPDX-FileCopyrightText: 2026 Dingtaiqi
# SPDX-License-Identifier: Apache-2.0
#
# iscsi_ref_up.sh - bring up a THROWAWAY iSCSI target on this host, and capture it.
#
# WHY THIS EXISTS
# ---------------
# The Windows iSCSI bridge in this project has a write path that works only up to one
# first burst (64 KiB): anything larger needs the target to send an R2T, and Windows
# answers every R2T this bridge sends with "Target sent an invalid iSCSI PDU"
# (iScsiPrt event 23, STATUS_NO_MEMORY) and drops the connection.  Thirteen
# hypotheses were falsified without it (DESIGN 8.60), because the bytes are already
# field-for-field correct against struct iscsi_r2t_hdr - so what is needed is not
# another guess but a REFERENCE: a target whose R2T Windows accepts, so the two can be
# compared byte by byte.
#
# tgt is that reference here: a mature userspace iSCSI target (Arch package `tgt`)
# that Windows initiators interoperate with.  Nothing of the user's storage is
# involved: the LUN is a scratch file under /tmp, created by this script, and the only
# initiator allowed to touch it is the Windows box on the LAN.
#
# USAGE
#   sudo ./iscsi_ref_up.sh          # install if needed, create the LUN, start tgtd, start tcpdump
#   sudo ./iscsi_ref_up.sh down     # stop tgtd and tcpdump, remove the scratch LUN
#
# OUTPUT TO LOOK AT
#   /tmp/iscsi_ref/capture.txt   tcpdump -X of port 3260 (the R2T is in here)
#   /tmp/iscsi_ref/tgtd.log      tgt's own log
#   tgtadm --mode target --op show

set -e

LUN_DIR=/tmp/iscsi_ref
LUN=$LUN_DIR/lun0.img
LUN_MB=64
IQN=iqn.2024-01.local.rdma:iscsi-ref
CONF=$LUN_DIR/tgt.conf
# The Windows box, i.e. the only initiator allowed to see this LUN.
INITIATOR=192.168.1.2
PORT=3260

if [ "$(id -u)" != "0" ]; then
    echo "must run as root:  sudo $0 $*" >&2
    exit 1
fi

# ---- tear down ------------------------------------------------------------
if [ "$1" = "down" ]; then
    pkill -f 'tcpdump -i .* port 3260' 2>/dev/null || true
    pkill tgtd 2>/dev/null || true
    sleep 1
    rm -rf "$LUN_DIR"
    echo "stopped tgtd/tcpdump and removed $LUN_DIR"
    exit 0
fi

# ---- address of the LAN interface ----------------------------------------
IP=$(ip -4 -o addr show scope global | awk '{print $4}' | cut -d/ -f1 | grep '^192\.168\.1\.' | head -1)
IFACE=$(ip -4 -o addr show scope global | awk '/192\.168\.1\./ {print $2; exit}')
if [ -z "$IP" ] || [ -z "$IFACE" ]; then
    echo "no 192.168.1.x address found; is the LAN interface up?" >&2
    ip -4 -o addr show scope global >&2
    exit 1
fi
echo "serving on $IP ($IFACE), initiator allowed: $INITIATOR"

# ---- packages -------------------------------------------------------------
if ! command -v tgtd >/dev/null 2>&1; then
    echo "installing tgt and tcpdump ..."
    pacman -S --noconfirm --needed tgt tcpdump
fi

# ---- scratch LUN ----------------------------------------------------------
mkdir -p "$LUN_DIR"
if [ ! -f "$LUN" ]; then
    echo "creating a ${LUN_MB} MiB scratch LUN at $LUN"
    truncate -s "${LUN_MB}M" "$LUN"
fi

cat > "$CONF" <<EOF
# generated by iscsi_ref_up.sh - throwaway reference target
<target $IQN>
    backing-store $LUN
    initiator-address $INITIATOR
    write-cache off
</target>
EOF

# ---- start the target -----------------------------------------------------
pkill tgtd 2>/dev/null || true
sleep 1
# --iscsi portal pins it to the LAN address, so the RoCE side is untouched.
# Two attempts, because the config-file spelling differs between tgt builds: first
# with -C, then by installing the config as a drop-in for the system default.
if ! tgtd -C "$CONF" --iscsi portal=$IP:$PORT 2>"$LUN_DIR/tgtd.err"; then
    echo "tgtd -C did not start it; falling back to /etc/tgt/conf.d/"
    mkdir -p /etc/tgt/conf.d
    cp "$CONF" /etc/tgt/conf.d/iscsi_ref.conf
    tgtd --iscsi portal=$IP:$PORT 2>"$LUN_DIR/tgtd.err" || true
fi
sleep 2
if ! pgrep tgtd >/dev/null 2>&1; then
    echo "tgtd is not running:" >&2
    cat "$LUN_DIR/tgtd.err" >&2
    exit 1
fi

# ---- capture the wire -----------------------------------------------------
pkill -f 'tcpdump -i .* port 3260' 2>/dev/null || true
: > "$LUN_DIR/capture.txt"
nohup tcpdump -i "$IFACE" -s 0 -X -l "tcp port $PORT" >> "$LUN_DIR/capture.txt" 2>"$LUN_DIR/tcpdump.err" &
sleep 2

echo
echo "=== targets ==="
tgtadm --mode target --op show | sed -n '1,40p'
echo
echo "=== listening ==="
ss -ltnp 2>/dev/null | grep ":$PORT" || echo "(ss showed nothing on $PORT)"
echo "=== capture ==="
echo "  $LUN_DIR/capture.txt   ($(wc -l < "$LUN_DIR/capture.txt" 2>/dev/null || echo 0) lines so far)"
echo
echo "Now, from Windows: connect the iSCSI initiator to $IP:$PORT and WRITE 64 KiB to"
echo "the disk, then read $LUN_DIR/capture.txt (or scp it back)."
echo "Stop everything with:  sudo $0 down"
